services:
  - type: web
    name: consumochoza
    runtime: java
    plan: free
    rootDir: consumochoza
    buildCommand: chmod +x ./mvnw && ./mvnw -DskipTests clean package
    startCommand: java -Dserver.port=$PORT -jar target/consumochoza-0.0.1-SNAPSHOT.jar
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
