spring.application.name=consumochoza
server.port=${SERVER_PORT:8085}
server.address=0.0.0.0

api.base-url=${API_BASE_URL:http://localhost:8081/api}

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
management.endpoint.health.probes.enabled=true

info.app.name=Consumo Choza
info.app.version=0.0.1-SNAPSHOT

spring.profiles.default=dev

server.error.include-message=never
server.error.include-binding-errors=never

logging.level.org.springframework.web=INFO
logging.level.org.springframework.web.reactive.function.client=INFO
