spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.hbm2ddl.auto=update
spring.sql.init.mode=never
spring.jpa.show-sql=false

# Fuerza dialecto para evitar error de Hibernate cuando no puede leer metadata
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# DataSource por variables de entorno de Render
spring.datasource.url=${SPRING_DATASOURCE_URL:${DB_URL:jdbc:postgresql://dpg-d69qud6sb7us73d0qv2g-a:5432/pisipapi2}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${DB_USER:pisip_user}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:}}
spring.datasource.driver-class-name=org.postgresql.Driver
